### ISSUE TITLE
Funkce setIsPerson vrací false, když právní forma v xml (KPF) je 424 nebo 425

### ISSUE THREAD

**Issue by vistacky** [h4kuna/ares#12]
IČ fyzické osoby ze Slovenska vrací false, protože je označená jako "zahraniční" právní forma. Mám za to, že právní formy 424 a 425 by měli být podle https://wwwinfo.mfcr.cz/ares/aresPrFor.html.cz označené, jako fyzické.

**Comment by h4kuna** [comment]
Ahoj, můžeš poslat pull request?

**Comment by vistacky** [comment]
Jasný, je to tam.

**Comment by h4kuna** [comment]
Musíš to poslat jako pull request jinak nebudeš jako autor.

**Comment by vistacky** [comment]
Tak teď už by to mělo být jako pull request.

**Comment by h4kuna** [comment]
vyřešeno #13
