### ISSUE TITLE
house_number je null

### ISSUE THREAD

**Issue by GEp1c** [h4kuna/ares#16]
Ahoj, `house_number` může být `null`, protože v ARESu nemusí být doplněny `AA->CD` a `AA->CO`.
`house_number` ve tvém formátu se ale může nacházet v `AA->CA`.

IČO, u kterého se to projevuje: **26713250**

**Comment by h4kuna** [comment]
Released version 1.4.8 1d62985fe62ce470ec080a5a611c5a4734a3b569

Thank you!
