### ISSUE TITLE
Firmy se skupinovým DPH

### ISSUE THREAD

**Issue by radimvaculik** [h4kuna/ares#22]
U firem, které mají skupinové DIČ, to vrací špatné DIČ.

https://wwwinfo.mfcr.cz/cgi-bin/ares/darv_bas.cgi?ico=49240901

```xml
<D:DIC zdroj="DPH">Skupinove_DPH</D:DIC>
```

Lze poznat podle 6. znaku v priznaku - viz dokumentace https://wwwinfo.mfcr.cz/ares/ares_xml_basic.html.cz

**Comment by h4kuna** [comment]
Ok, uděláš PR?

**Comment by h4kuna** [comment]
Kde je ten správný DIČ? Nějak mi není jasné jak se k němu dostat.

**Comment by radimvaculik** [comment]
V tom je ten fór. Není tam.

**Comment by h4kuna** [comment]
A jak by jsi si představoval že se má knihovna zachovat?

**Comment by radimvaculik** [comment]
Ideálně vrátit spravný DIČ. Pořádně jsem to nezkoumal. Možná existuje nějaké API, kde se k DIČ dá dostat.

**Comment by h4kuna** [comment]
A můžeš na to mrknout? Třeba během následujících několika dní?

**Comment by radimvaculik** [comment]
Jo, jasne. Stejne to potrebuji.

**Comment by radimvaculik** [comment]
Hele, dal jsem tomu asi hodinu, trochu pogooglil, prosel specifikace, ale bohuzel nevim, jak se k DIC dostat 🤷

**Comment by h4kuna** [comment]
Díky za zprávu, nechám otevřené issue.

**Comment by h4kuna** [comment]
@radimvaculik není náhodou skupinové DIČ ve tvaru CZ<IČ> v tvém případě by DIČ byl `CZ49240901`?

**Comment by radimvaculik** [comment]
@h4kuna Bohužel. Viz https://rejstrik-firem.kurzy.cz/49240901/raiffeisenbank-as/. DIČ je **CZ699003154**.

**Comment by h4kuna** [comment]
@radimvaculik Já jsem zase našel stránku, na kterou jsem se dostal z ARESu https://adisspr.mfcr.cz/dpr/DphReg?id=1&pocet=1&fu=&OK=+Search+&ZPRAC=RDPHI1&dic=49240901 kde DIČ je `CZ49240901` a to DIČ co uvádíš je neplatné, viz `Registrace platná do: 31.12.2012` Ale jsou to jen moje domněnky... Chtělo by to aby to někdo povolanější potvrdil.

**Comment by h4kuna** [comment]
Koukám že ta stránka si nedrží stav podle url
![Snímek obrazovky z 2022-08-17 09-32-14](https://user-images.githubusercontent.com/335722/185060970-5d14f0be-494a-4c01-b40b-c1364fa39c42.png)

**Comment by h4kuna** [comment]
Mohu říct že jsem to taky potřeboval. Nenašel jsem jak lehce to implementovat.
Zvolil jsem cestu parsování html ze stránek https://adisspr.mfcr.cz/dpr/DphReg kde ti to řekne že je ve skupině, a pokud je udělám znova dotaz na to nové DIČ. Toto je tak nestandardní, že to sem nepřidám. Předpokládám, že to bude náchylné na rozbití.

**Comment by h4kuna** [comment]
Možná cesta: https://adisspr.mfcr.cz/pmd/dokumentace/webove-sluzby-spolehlivost-platcu

**Comment by h4kuna** [comment]
Vyřešeno novou verzí ARES2

**Comment by Prochy20** [comment]
Ahoj,

shodou okolností v tuhle chvíli řeším ten samý problém. Bohužel jsem v ARES2 ale nikde neobjevil, jak zjistit skupinové DIČ - můžu tě poprosit o radu, jak jsi to vyřešil?

Díky.

**Comment by h4kuna** [comment]
Podle diskuse #30 nevyřešil :)

**Comment by hubipe** [comment]
Psal jsem si opět s panem Sádlíkem z MFČR ohledně nového ARESu a skupinových registrací k DPH. Jeho vyjádření:

> Dobrý den,
> od poskytovatele dat jsme obdrželi informaci, že zapracování našich požadavků ke skupinovému DPH je možné až v průběhu příštího roku. 
> To znamená, že jsme nyní nuceni přejít na variantu původního Aresu.
> Do služby EkonomickySubjekt (jadro) byl vložen atribut "dicSkDph" (dočasně vyplněn „N/A“). Brzy začneme doplňovat data ze současného systému Ares.
> Problém se zobrazováním skupinového DPH by se tímto krokem měl tedy vyřešit.
> Omlouváme se za komplikace.

Takže to vypadá, že v této property asi budou hodnoty „Skupinove_DPH“ jako ve starém ARESu. Nebo taky ne, tady člověk nikdy neví.

**Comment by buchtajz** [comment]
Ahoj,
aktuálně dicSkDph vrací místo "N/A" rovnou DIČ subjektu (ale ne skupiny). 😭

https://ares.gov.cz/ekonomicke-subjekty-v-be/rest/ekonomicke-subjekty/49240901
```
...zkráceno
{
"ico":"49240901",
"obchodniJmeno":"Raiffeisenbank a.s.",
"dic":"CZ49240901",
"icoId":"49240901",
"dicSkDph":"CZ49240901"
}
```

**Comment by h4kuna** [comment]
Pěkný..., nicméně se to validuje přes adis, takže, knihovna stále vrací null na DIČ.
