### ISSUE TITLE
loadData and loadXml has wrong array type

### ISSUE THREAD

**Issue by drakous79** [h4kuna/ares#25]
Hello. Methods loadData and loadXml are expecting array $options = [string => mixed] according to
@param array<string, mixed> $options
but
array $options = [CURLOPT_CONNECTTIMEOUT => 30]
is <int, mixed>

**Comment by h4kuna** [comment]
You have right, fixed in master.
Thank you

**Comment by drakous79** [comment]
Thank you very much for fast fix
