### ISSUE TITLE
Class "GuzzleHttp\Psr7\HttpFactory" not found at any Guzzle version 7.5+

### ISSUE THREAD

**Issue by BigOHenry** [h4kuna/ares#29]
On `h4kuna/ares` at version `2.0.4` getting this error:

![obrazek](https://github.com/h4kuna/ares/assets/15823552/799109f8-e1a2-4881-b0a9-667e4ae18d86)

There is no `GuzzleHttp\Psr7\HttpFactory`  class at `GuzzleHttp\Psr7\...` namespace (version 7.5+)

**Comment by h4kuna** [comment]
Hello, please try fix from master. After you will confirm it. I will release new version.

**Comment by h4kuna** [comment]
released
