### ISSUE TITLE
ARES XML služby končí k 31.10.2023

### ISSUE THREAD

**Issue by BigOHenry** [h4kuna/ares#30]
Nový ares (REST API): [zdroj](https://wwwinfo.mfcr.cz/ares/)
> Vážení uživatelé,
> tímto vám oznamujeme, že jsme spustili pilotní provoz modernizovaného Informačního systému ARES, který je dostupný na adrese "ares.gov.cz".
> 
> Technickou dokumentaci - katalog veřejných služeb pro vývojáře je možné získat:
> 
[ARES-Technicka-dokumentace-Katalog-verejnych-sluzeb (PDF, 1183 kB)](https://www.mfcr.cz/assets/attachments/2023-08-01_ARES-Technicka-dokumentace-Katalog-verejnych-sluzeb.pdf)
[AresRestApi-verejne (.JSON, 326 kB)](https://www.mfcr.cz/assets/attachments/2023-08-01_AresRestApi-verejne.json)
> 
> 
> Původní i modernizovaný systém bude provozován souběžně do 30. 9. 2023. Nezbytné změny doporučujeme provést co nejdříve. V případě dotazů se prosím obracejte na email: [aresmfcr@mfcr.cz](mailto:aresmfcr@mfcr.cz)

**Comment by h4kuna** [comment]
Pěkný, to je pro mě celkem šibeniční termín.

**Comment by h4kuna** [comment]
Vývoj je ve větvi [3.x](/h4kuna/ares/tree/3.x)

**Comment by BigOHenry** [comment]
Ten jeden měsíc je za mě nepochopitelnej. Nevím proč tak spěchají.

**Comment by josefsabl** [comment]
> Vývoj je ve větvi [3.x](/h4kuna/ares/tree/3.x)

Prosím, v jakém stádiu je vývoj? Je to již nějak použitelné v alpha režimu? Pracuji na nové aplikaci, kde ARES využijeme, tak bych byl early adopter nové verze a mohl nějak pomoci s vychytáváním much 😄 .

**Comment by h4kuna** [comment]
Teď jsem to dodělal do stavu, že to implementuju do aplikace a nechám to tak týden běžet. Takže pokud chceš, můžeš

```
composer require h4kuna/ares:3.x-dev
```

Příklad v dokumentaci je funkční.

[ ] nesepsal jsem nekompatibility
[ ] musím doplnit aliasy pro přesunuté třídy

**Comment by h4kuna** [comment]
Tak oficiálně je to připravené na alfa testování, není tam nic co bych chtěl implementovat.

**Comment by BigOHenry** [comment]
Díky. Vypadá to že základ funguje. Jen ještě otázka, máš v plánu implementovat další endpointy? (RES, VR, atd.)

**Comment by h4kuna** [comment]
Super že jsi to našel, nicméně i sem přidám odkaz na [changelog](https://github.com/h4kuna/ares/blob/3.x/changelog.md)

**Comment by BigOHenry** [comment]
Narazil jsem na jednu věc. Plátce DPH. 
```
$data->tin = Strings::trimNull($json->dic ?? null);
		$data->vat_payer = (bool) $data->tin;
```
To, že má osoba DIČ ještě neznamená že je plátce DPH. Může být jen jako identifikovaná osoba. Hodnota atributu **vat_payer** je tedy za mě špatně.

Hodnota plátce DPH vrací pouze ekonomicke-subjekty-szr -> zaznamSzr -> platceDPH

**Comment by h4kuna** [comment]
To znamená udělat dotaz na další endpoint... tomu jsem se chtěl vyhnout

**Comment by hubipe** [comment]
To je hloupost, ekonomicke-subjekty-szr je endpoint pro Záznamy Zemědělského registru. Firmy a živnostníci tam nebudou. Obávám se, že ARES vůbec informaci o plátcovství DPH nezná. Na ověření plátce DPH slouží VIES.

@h4kuna V changelogu píšeš:

> zmizela metoda isGroupVat() ARES již vrací DIČ pro skupinové DPH

Jenže ARES vrací DIČ pro skupinové DPH chybně...

Viz např.: https://ares.gov.cz/ekonomicke-subjekty-v-be/rest/ekonomicke-subjekty/02445344 - ARES vrací DIČ 02445344, ale správné DIČ subjektu je CZ699004845
nebo: https://ares.gov.cz/ekonomicke-subjekty-v-be/rest/ekonomicke-subjekty/49240901 - ARES vrací DIČ 49240901, ale správné DIČ subjektu je CZ699003154

Psal jsem před chvílí na aresmfcr@mfcr.cz s dotazem, jestli bude ARES vracet správná DIČ v případě skupinových registrací k DPH. Uvidíme co odpoví, jestli odpoví...

**Comment by BigOHenry** [comment]
@hubipe Co je hloupost? Vyhodnocení plátce DPH je špatně implementované. Nepsal jsem že szr vrací vše, jen jsem napsal který endpoint to vrací :-)

Jinak máš pravdu, ARES (žádný endpoint) tedy nevrací plátce DPH pro všechny subjekty.

Také potvrzuji špatné skupinové DIČ.
Díky a dej pak prosím vědět až odpoví (jestli) :-)

@h4kuna Bude to tedy spíše o tom atribut vat_payer úplně vyhodit.

**Comment by SvatoplukHus** [comment]
@mabar Informace "možná" je poměrně málo použitelná.

Správné je nevracet info o plátcovství DPH, protože ho Ares neposkytuje.

Dedukovat nepřesné informace je asi mimo scope této knihovny.

**Comment by pionl** [comment]
@SvatoplukHus nemyslím si že je to mimo scope knihovny. Obecně ARES knihovnu použiješ aby si doplnil fakturační údaje a potřebuješ identifikaci i o DPH :)

Co se týče jak evidovat typ DPH, tak bych šel jak to má ISDOC (a my interně).

case ValueAddedTax = 'VAT';
case TaxIdentificationNumber = 'TIN';

nebo null.

:)

**Comment by BigOHenry** [comment]
@SvatoplukHus má podle mě pravdu.
@pionl Jenže to že má někdo DIČ, neznamená vůbec nic. Já třeba DIČ mám, ale plátce DPH nejsem (identifikovaná osoba). Je hromada případů kdy DIČ osoby mají a plátci nejsou.
A jak psal @hubipe "Na ověření plátce DPH slouží VIES." A my ho také na to používáme. Za mě není důvod, aby si tahle super knihovna vymýšlela data :-)

A né každý používá tuto knihovnu na doplnění fakturačních údajů. Někdo ji třeba používá i v jiném prostředí, kde ty data MUSÍ být správná.

**Comment by h4kuna** [comment]
Říkám si zda by se nedalo chytit, zda je plátce DPH či není `seznamRegistraci { "stavZdrojeDph":"AKTIVNI"}`

---

Z historických důvodů jsem držel kompatibilitu a ponechal některé možnosti.
Je potřeba mít možnost třídu [Data](/h4kuna/ares/blob/3.x/src/Ares/Core/Data.php) vyměnitelnou za vlastní entitu? 
  - odstranil bych DataInterface

Je potřeba mít možnost ovlivnit plnění entity?
  - odstranil bych JsonToDataTransformerInterface

**Comment by BigOHenry** [comment]
@h4kuna Hele to je otázka. Možná by tam cesta byla. Moje ičo je: 05560438

**Comment by h4kuna** [comment]
@BigOHenry cesta tam není :) u tebe jako identifikované osoby je uveden `"stavZdrojeDph":"AKTIVNI"`

**Comment by BigOHenry** [comment]
@h4kuna Taky jsem koukal. Bohužel není.

**Comment by hubipe** [comment]
@BigOHenry @h4kuna Koukám na to tvé DIČ. Na stránkách MFČR je v registru DPH skutečně tvoje DIČ uvedeno, jako identifikovaná osoba:
![image](https://github.com/h4kuna/ares/assets/617880/968031e9-3cf6-4c40-a95e-30b474df2aa8)
narozdíl třeba ode mě, kde je uvedeno _plátce_:
![image](https://github.com/h4kuna/ares/assets/617880/3d1b386c-6bce-4fd0-99e0-5beabab142ca)

VIES však tvé DIČ potvrdí, jako plátce:
![image](https://github.com/h4kuna/ares/assets/617880/f1dd4af1-e11e-47a4-ac23-23cf9399df1a)

Tedy z mého pohledu, když by knihovna zachovala příznak _vat_payer_, pak je za mě validní, aby v případě identifikovaných osob vracela _TRUE_. (Protože pokud někomu vystavuješ fakturu, přidáváš na ni DPH, které si může plátce DPH odpočítat, je to tak?) Ale stále nejsem přesvědčen o tom, že by knihovna pro vytahování dat z ARESu měla vůbec tuto property vracet. Stejně to není směrodatné a důležité je to, co vrací VIES.

**Comment by hubipe** [comment]
@BigOHenry Aha, takže pro zahraniční plátce se identifikovaná osoba chová jako plátce DPH (vystavují faktury v režimu přenesené daňové povinnosti), ale v tuzemském styku identifikovaná osoba nevystupuje jako plátce DPH, takže potenciální příjemce tvých služeb si DPH odpočítat nemůže.
Koukám ještě do starého ARESu, a tam v tagu PSU jsi také označen příznakem A pro registr DPH. Tzn. vlastně ARES vrací to stejné, co VIES - jen to, jestli jsi nebo nejsi v registru DPH, nikoliv v jakém režimu tam jsi. Takže ve dvojkové verzi knihovny jsi (nejspíš) taky označen jako _vat_payer_.
Takže pokud @h4kuna příznak v ARES _vat_payer_ ponechá, pak mi přijde, že by se měl chovat stejně, jako ve dvojkové verzi - tzn. vracet TRUE, pokud existuje záznam v registru DPH, tedy `"stavZdrojeDph":"AKTIVNI"`. Ale je pravdou, že pro identifikované osoby je to zavádějící.

**Comment by BigOHenry** [comment]
@hubipe Ano, ve dvojkové verzi jsem označen jako vat_payer.

No ona je pak další otázka, jestli nejsou nějaké případy, kdy osoba má DIČ, ale z nějakého důvodu plátce není. Například že byl a již plátce není, ale DIČ mu zůstává. Ale to jsou hypotetické scénáře, u kterých netuším jestli jsou reálné. To by se dalo případně kombinovat se `stavZdrojeDph` jak píšeš.

**Comment by h4kuna** [comment]
Stav zdroje jsem upravil. Jestli jsi nebo nejsi identifikovaná osoba už nejde zjistit. Vlastnosti jsem označil jako deprecated, aby se škrtnuli v IDE, ale zatím je neplánuju odebrat.

**Comment by h4kuna** [comment]
Identifikovaná osoba půjde [zjistit z API](https://github.com/h4kuna/ares/issues/22#issuecomment-1705189981) to bych chtěl dodělat. Fór je v tom že tam je SOAP, problém to není, jen co služba to jiná technologie. Pokud by chtěl někdo na tom začít dělat, bylo by to fajn :)

**Comment by h4kuna** [comment]
Pokud bych napojil i VIES, tak bych mohl dát dohromady všechny relevantní data :)

**Comment by h4kuna** [comment]
@BigOHenry na starých datech máš taky DIČ https://wwwinfo.mfcr.cz/cgi-bin/ares/darv_bas.cgi?ico=05560438 takže jsi byl vždy vat_payer podle knihovny. Ta detekce se chovala stejně i předtím. Jen nikdo N let to neřešil :)

**Comment by BigOHenry** [comment]
@h4kuna Je to tak a navíc DIČ mám tak max rok, takže jsem to předtím neřešil (a nic moc jsem o tom ani nevěděl) :)

**Comment by h4kuna** [comment]
Ono v 90-95% případů budou data správně.

**Comment by BigOHenry** [comment]
@h4kuna Tady jsem vyhrabal starou a basic, ale funkční implementaci ADIS. Nevím jestli ti k něčemu bude ale dám ji sem :)
```
$xml = '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
            <soapenv:Body>
            <StatusNespolehlivyPlatceRequest xmlns="http://adis.mfcr.cz/rozhraniCRPDPH/">
            <dic>'.$dic.'</dic>
            </StatusNespolehlivyPlatceRequest>
            </soapenv:Body>
            </soapenv:Envelope>';

$request = curl_init();

$url = 'http://adisrws.mfcr.cz/adistc/axis2/services/rozhraniCRPDPH.rozhraniCRPDPHSOAP';

curl_setopt($request, CURLOPT_URL, $url);
curl_setopt($request, CURLOPT_CAINFO, $this->wwwDir . "/../resources/API/cacert.pem");

if($this->serviceModel->isProxy()) {
    curl_setopt($request, CURLOPT_USERPWD, $this->domain_user['user'] . ":" . $this->domain_user['password']);
    curl_setopt($request, CURLOPT_PROXY, $this->https_proxy['host'].':'.$this->https_proxy['port']);
}

$headers = array(
    'Content-Type:text/xml',
);
curl_setopt($request, CURLOPT_HTTPHEADER, $headers);

curl_setopt($request, CURLOPT_RETURNTRANSFER, true);
curl_setopt($request, CURLOPT_CONNECTTIMEOUT ,400);
curl_setopt($request, CURLOPT_TIMEOUT, 400);

curl_setopt( $request, CURLOPT_POST, true );

curl_setopt($request, CURLOPT_POSTFIELDS, $xml);

$result_main = curl_exec($request);
$result = preg_replace("/(<\/?)(\w+):([^>]*>)/", "$1$2$3", $result_main);

$saved  = libxml_use_internal_errors(true);
$xml = simplexml_load_string($result);
$errors = libxml_get_errors();
libxml_use_internal_errors($saved);

if ($xml === false) {
    if(count($errors) > 0) {
        // log $errors
    } else if (curl_errno($request)) {
        // log curl_error($request)
    } else {
        // log $result_main
    }

    curl_close($request);
} else {
    if (curl_errno($request)) {
        // log curl_errno($request)
    } else {
        $json = json_encode($xml);
        $data = json_decode($json, true);
        // $data obsahují data z response jako pole
    }
}

```

**Comment by hubipe** [comment]
@h4kuna  Potvrzuju; teď jsem zkoušel ten SOAP, a typ registrace jde vytáhnout za předpokladu, že známe DIČ:

```php
$soap = new SoapClient('https://adisrws.mfcr.cz/dpr/axis2/services/rozhraniCRPDPH.rozhraniCRPDPHSOAP');
dumpe($soap->getStatusNespolehlivySubjektRozsireny(['dic' => '8702080024']));
```

v response je pak typSubjektu, který podle dokumentace může nabývat hodnot:
```xml
<xsd:enumeration value="PLATCE_DPH"/>
<xsd:enumeration value="IDENTIFIKOVANA_OSOBA"/>
<xsd:enumeration value="NENALEZEN"/>
```

![image](https://github.com/h4kuna/ares/assets/617880/303430dc-c6af-457a-bbb1-2038acda1f94)

Ale stejně to neřeší skupinové DPH, u kterého prostě z ARESu DIČ skupiny nedostaneme:
![image](https://github.com/h4kuna/ares/assets/617880/9cce13d5-eadc-4174-8de4-95a4281cdb5d)
![image](https://github.com/h4kuna/ares/assets/617880/2c60f404-3145-407b-962f-3e4f02d429a3)

**Comment by hubipe** [comment]
Dobrá zpráva, odepsali mi z MFČR:

> Dobrý den,
> o požadavku na Skupinové DPH víme a pracujeme na tom. Snažíme se o to, aby se vracelo DIČ skupiny nikoliv pouze text „Skupinove_DPH“. Tyto údaje přebíráme z Generálního finančního ředitelství, které nám již zaslalo testovací dávku, kterou nyní analyzujeme a snažíme se najít vhodné řešení.
> 
> S pozdravem
> Jan Sádlík
> oddělení Informační systémy |Information Systems
> MINISTERSTVO FINANCÍ | MINISTRY OF FINANCE
> Letenská 15, 118 10 Praha | Prague – Czech Republic

**Comment by h4kuna** [comment]
Přidal jsem ADIS jako další službu s tím že to zatím nijak neovlivňuje výsledky z ARESu. @BigOHenry použil jsem pro inspiraci ten kód, protože lze pak použít PSR standardy, namísto nativní SoapClient.

**Comment by h4kuna** [comment]
Doplnil jsem, aby ADIS validoval výsledky z ARESu. [Přehledná tabulka](https://github.com/h4kuna/ares/blob/3.x/changelog.md#chov%C3%A1n%C3%AD-validace-pomoc%C3%AD-adis)

**Comment by nufue** [comment]
FYI
> Na základě zpětné vazby jsme se rozhodli prodloužit souběžný provoz původního a modernizovaného informačního systému ARES do 31. 10. 2023.

**Comment by h4kuna** [comment]
Pokud používáte již tuto alfa verzi, doporučuji aktualizovat, změnili vstupní data a knihovna se chová špatně. Již opraveno #35

**Comment by h4kuna** [comment]
Vydána verze [3.0.0](https://github.com/h4kuna/ares/releases/tag/v3.0.0)

**Comment by hubipe** [comment]
Jen pro info – vypnutí starého ARESu se odkládá na konec roku. Co se týče skupinových registrací k DPH, tak to v novém ARESu ještě pořád neimplementovali.

**Comment by arziel12** [comment]
FIY: DIČ má u nás každý subjekt, získáváš ho při registraci na FÚ k dani z příjmu a je to identifikátor se kterým se s FÚ komunikuje i jako neplátce DPH. Takže úplně správně by ho měl vracet každý kontakt, ale jak víme, mají v tom registru bordel hlavně oni :)

**Comment by h4kuna** [comment]
Je to pravda, ale já ten DIČ pro neplátce nedostanu...

**Comment by h4kuna** [comment]
> Dobrá zpráva, odepsali mi z MFČR:
> 
> > Dobrý den,
> > o požadavku na Skupinové DPH víme a pracujeme na tom. Snažíme se o to, aby se vracelo DIČ skupiny nikoliv pouze text „Skupinove_DPH“. Tyto údaje přebíráme z Generálního finančního ředitelství, které nám již zaslalo testovací dávku, kterou nyní analyzujeme a snažíme se najít vhodné řešení.
> > S pozdravem
> > Jan Sádlík
> > oddělení Informační systémy |Information Systems
> > MINISTERSTVO FINANCÍ | MINISTRY OF FINANCE
> > Letenská 15, 118 10 Praha | Prague – Czech Republic

Vypadá to že vše funguje, již dostávám skupinové DPH.
