### ISSUE TITLE
Nepotřebná závislost Nette/Utils

### ISSUE THREAD

**Issue by ondrejznojil** [h4kuna/ares#33]
Ahoj Milano,

v prvé řadě děkuji, že tento balíček (a jiné) a také za to, jak rychle jsou reagoval na změnu API našeho milého ministerstva. 

Nasazuji alphu nové verze na projekt a narazil jsem na konflikt s Nette/Utils. Máme pouze 2.4, tak jsem si udělal fork. Nicméně mě zarazilo, že po provedení downgrade na 2.4 všechny testy v pohodě prošly a podle všeho je to prostě zpětně kompatibilní. Z tohoto důvodu bych navrhl nechat jako kompatibilní i starší verzi utils, protože tomu tak je.

Nechci tu být za idiota, co ničím nepřispěje a jen nadává, ale zvažoval jsi Nette/Utils nepoužít vůbec? V knihovně se používá velmi zřídka na základní věci (hlavně JSON), což umí PHP i nativně a vytváří se tím závislost na balíček, který se používá ve framework a může to na spoustě projektů kolidovat.

Pokud nic z toho nechceš řešit, tak to issue prostě zavři.

tldr;
1. Nette/Utils není v knihovně potřeba
2. Zpětnou kompatibilitu balíčku mohou zařídit i nižší verze

**Comment by h4kuna** [comment]
1. nette/utils řeší edge case pro parsování z jsonu, nechám
2. zvážím, kouknu na to

**Comment by h4kuna** [comment]
přidal jsem možnost nette/utils 2.0

**Comment by ondrejznojil** [comment]
Super, díky!
