### ISSUE TITLE
nazevCastiObce přednější před nazevOkresu

### ISSUE THREAD

**Issue by juniwalk** [h4kuna/ares#36]
Zdravím,
aktualizoval jsem na novou verzi a vrací mi to teď špatně adresu.

V [JsonToDataTransformer.php](https://github.com/h4kuna/ares/blob/master/src/Ares/Core/JsonToDataTransformer.php#L32C87-L32C101) bych řekl, že `nazevCastiObce` by mělo být před `nazevOkresu`.
```php
$data->city_district = Strings::trimNull($json->sidlo->nazevOkresu ?? $json->sidlo->nazevCastiObce ?? null);
```

**Comment by h4kuna** [comment]
Bylo by nějaké konkrétní IČO? Očekávaný výsledek. Potřeboval bych konkrétní data.

**Comment by juniwalk** [comment]
Ok tak moje ičo 08975884, předpokládaná adresa je "Merklovice 25, Vamberk, 51754" dostávám "Rychnov nad Kněznou 25, Vamberk, 51754"

Adresu si skládám takto:
```php
return (object) [
	'company' => $ares->company,
	'street' => ($ares->street ?? $ares->city_district).' '.$ares->house_number,
	'city' => $ares->city,
	'zip' => $ares->zip,
	'corporateId' => $ares->in,
	'vatNumber' => $ares->tin,
];
```

**Comment by juniwalk** [comment]
Díky moc!

**Comment by h4kuna** [comment]
@juniwalk Ahoj, prosím tě změnil jsi adresu nebo Ares vrací nesmysl? Nově: "Letná 530/41, Liberec XII-Staré Pavlovice, 46001 Liberec" Než opravím testy tak si to chci ověřit.

**Comment by juniwalk** [comment]
Ahoj, ano měnil jsem adresu takže upravit testy. Díky.
