### ISSUE TITLE
Ares pro starší verze PHP (7.1)

### ISSUE THREAD

**Issue by pmalecek** [h4kuna/ares#38]
Ahoj,

Využívám tuto knihovnu pro získávání dat v poměrně starém projektu, který není úplně jednoduché upgradovat (je to projekt, který vznikal cca 8 let, bezpečně ještě běží na PHP 7.1, ale novější už ne). Neplánuješ vytvořit ještě nějakou aktuální "legacy" verzi, která by správně komunikovala s novým ARESem, ale byla použitelná i u starších projektů? Využívám verzi 1.4.14. 

Díky za info.

**Comment by pmalecek** [comment]
Aktuálně jsem to tedy vyřešil nasazením knihovny na jiném serveru s PHP 8.2 a voláním (pomocí HTTP requestu) z projektu, čili problém vyřešen. Každopádně ta legacy podpora by možná nebyla na škodu.

**Comment by h4kuna** [comment]
Nechci. Můžeš to klidně udělat a poslat MR.

**Comment by h4kuna** [comment]
Tady jsou forky pro php 7.4. Nicméně nevypadají udržovaně.

- https://github.com/finwe/ares/commits/v3-php7.4/
- https://github.com/akaprizza/ares/commits/php74-support/
