### ISSUE TITLE
Adis error

### ISSUE THREAD

**Issue by danco12** [h4kuna/ares#39]
Ahoj,

```
<?php

require_once './vendor/autoload.php';
ini_set('zend.assertions', 0);
use h4kuna\Ares;
/** @var Ares\Ares $ares */
$ares = (new Ares\AresFactory())->create();
$in = '47673036';
$ares->loadBasic($in);
```

Zavolanie tohoto kodu s IN firmy, ktora ma aj TIN, napr. 47673036 vyhodi exception:

```
h4kuna\Ares\Exceptions\ServerResponseException
Missing tag "StatusNespolehlivySubjektRozsirenyResponse" in response.
```

Tato exception nesuvisi s Ares datami ale z datami z Adisu. Neslo by to upravit tak, aby v tomto pripade loadBasic() nevyhodil exception ale pri tych Adis datach by sa odchytila exception a Adis by sa nenasetoval (default je null, cize by to nemal byt problem)?

Pozri `h4kuna\Ares\Ares\Core\ContentProvider::load(string $in)`

**Comment by h4kuna** [comment]
Přidal jsem, odchycení exception 148ff26930b3ed03350698fa99d852ec5173ebe3, nevím jestli je to vhodný, protože to změní chování, takže je potřeba přidat nějakou metodu, která ti řekne jestli došlo k validaci.

**Comment by parisek** [comment]
Ahoj, zrovna také řeším, vyhazuje mi to stejnou chybu, ale když jsem debugoval, tak mi to hlásí:
`Váš požadavek byl z bezpečnostních důvodů zablokován. Číslo chyby: 8811346882115357625 https://epodpora.mfcr.cz/`
zřejmě blokují nějaké rozsahy, lokálně mi to funguje, ošetření funguje, díky moc za rychlé řešení

**Comment by pionl** [comment]
Přesunuli jsme servery na hetzner a taky nám to nefunguje :)

**Comment by pionl** [comment]
Reakce od ePodpory

> tato chybová hláška je velmi pravděpodobně způsobena skutečností, že portál Moje daně čelí DDoS útoku, který způsoboval jeho nedostupnost. Tuto bezpečnostní událost Finanční správa dočasně vyřešila tak, že zakázala přístup z jiných než českých IP adres. Není možné určit, jako dlouho bude tato událost trvat. Nicméně zároveň pracujeme na jiném řešení, do té doby však bude přístup na portál fungovat pouze z českých IP adres.
> Povolování výjimek pro jednotlivé zahraniční IP adresy není možné.
> Omlouváme se Vám za vzniklé nepříjemnosti.
>

**Comment by h4kuna** [comment]
Přidal jsem nový typ exception pokud adis selže, k datům ARESu se dostaneš, ale hned víš že neprošla validace. Za mě spokojenost s tímto řešením. Přidal jsem do readme.

**Comment by h4kuna** [comment]
vydaná verze 3.0.7
