### ISSUE TITLE
Chybějící zip, street, house_number pro specifické ičo

### ISSUE THREAD

**Issue by zraly** [h4kuna/ares#40]
Ahoj, pro IČO 25528351 dostávám tento výsledek:

```
active: true
   city: 'Trnava'
   company: 'KOMSOL CZ, s.r.o.'
   created: DateTimeImmutable #13701
   |  date: '1998-05-11 00:00:00.000000'
   |  timezone_type: 3
   |  timezone: 'Europe/Prague'
   dissolved: null
   city_district: null
   city_post: null
   in: '25528351'
   is_person: false
   legal_form_code: 112
   house_number: null
   street: null
   district: 'Třebíč'
   tin: 'CZ25528351'
   vat_payer: true
   zip: null
   country: 'Česká republika'
   country_code: 'CZ'
```

Přitom všechny údaje by v originále šly najít:

```
sidlo: stdClass #13706
   |  |  kodStatu: 'CZ'
   |  |  nazevStatu: 'Česká republika'
   |  |  kodKraje: 108
   |  |  kodOkresu: 3710
   |  |  nazevOkresu: 'Třebíč'
   |  |  kodObce: 591840
   |  |  nazevObce: 'Trnava'
   |  |  kodCastiObce: 168289
   |  |  textovaAdresa: '67401 Trnava 32, okres: Třebíč, Česká republika'
   |  |  cisloDoAdresy: '32'
   |  |  standardizaceAdresy: false
   |  |  pscTxt: '67401'
```

Sám jsem dříve bojoval v sestavování ucházejícího výstupu, protože těch variant je X. Pak jsem začal používat tvou knihovnu a jsem moc spokojený, ale tady jsem narazil. Je to vlastnost a mám si to vytáhnou sám, nebo to půjde vylepšit?

Díky moc

**Comment by h4kuna** [comment]
Vylepšíme :) Dej mi pár dní abych to mohl analyzovat a pak napíšu.

**Comment by h4kuna** [comment]
Jak píšeš, těch kombinací je mnoho, a vždy když někdo napíše, tak tu adresu dám do testů a takto postupně přidávám různě kombinace.

**Comment by h4kuna** [comment]
Zkus nainstalovat master.
```bash
composer remove h4kuna/ares
composer require h4kuna/ares:master
```

**Comment by zraly** [comment]
psč vrací, ale stále chybí ulice a číslo domu. `house_number` by určitě mělo být 32, tedy fallback z `cisloDoAdresy`.
Ulice - to je otázka, zda nechat null, když není ulice nebo nahradit názvem obce, tedy fallback z `nazevObce`, já jsem pro nahrazení.

**Comment by h4kuna** [comment]
Nahrazení bych nedělal, protože to samé je u malých vesnic. Němčice, nemá ulici, ale adresa je Němčice <číslo>. A u těchto malých obcí také nevyplňuji street, to by způsobilo nekompatibilitu.

Zkus update
```bash
composer update h4kuna/ares
```

**Comment by zraly** [comment]
Souhlas a funguje, díky moc

**Comment by h4kuna** [comment]
new release https://github.com/h4kuna/ares/releases/tag/v3.0.8
